# Site settings
title: "BIOINF 524/525"
email: bjgrant@umich.edu
description: > # this means to ignore newlines until "baseurl:"
   Winter 2017 BIOINF524/525 course at the University of Michigan that 
   introduces students to the fundamental principles and practices 
   of bioinformatics, biostatistics and systems biology.  
baseurl: "/bioinf525_w17" # the subpath of your site, e.g. /blog/
url: "http://bioboot.github.io/bioinf525_w17" 
twitter_username: bioboot
github_username:  bioboot

# Build settings
markdown: kramdown
